Adjust terminoloy for size
FirmwareHandoff/firmware_handoff pull request #25
Opened 2023-11-07 22:30 UTC by sjg20

The word 'size' is pretty generic and appears through the spec. It refers to the about of space currently used by the TEs, so rename it to used_size

The term `max_size` is a little confusing since it is really the current size of the TL including its spare space. Rename this to total_size indicating that is the total of all TEs and space space.

It also happens to match the devicetree terminology.

Fixes: #22

2023-11-08 21:22 UTC, jwerner-chromium approved these changes

2023-11-10 14:13 UTC, manish-pandey-arm approved these changes

2023-11-10 19:12 UTC, sjg20 commented
Dan are you able to review this one please? It is a name change so would like to get it in for the impls in progress

2023-11-15 20:14 UTC, sjg20 commented
ping for review, please

2023-11-15 22:44 UTC, stuyod01 approved these changes

2023-11-16 10:30 UTC, manish-pandey-arm approved these changes

2023-11-17 17:15 UTC, jmarinho approved these changes

2023-11-21 16:39 UTC, danh-arm requested changes
I'm fine with this PR in principle but I don't think it's complete. In particular handoff_list_diagram.svg needs updating with the new terminology (actually it's already out of date as it refers to length and max_length). Other places that may need changing:

- #144 Add used to "the size of an entry".
- #384 Remove word "total" in this line as it's now a bit confusing when referring to a target "used" size.
- #499 Add "used" appropriately

2023-11-21 17:41 UTC, danh-arm commented
One other little thing. It would be good to add "Fixes #22" or similar to the commit msg so the corresponding issue is automatically closed.

2023-12-19 21:19 UTC, sjg20 commented
> I'm fine with this PR in principle but I don't think it's complete. In particular handoff_list_diagram.svg needs updating with the new terminology (actually it's already out of date as it refers to length and max_length). Other places that may need changing:
> 
> * #144 Add used to "the size of an entry".
> * #384 Remove word "total" in this line as it's now a bit confusing when referring to a target "used" size.
> * #499 Add "used" appropriately

I couldn't quite figure all of those out, but I gave it a crack. Please can you check it again?

2023-12-21 17:20 UTC, danh-arm approved these changes

2023-12-21 17:20 UTC, danh-arm commented on source/transfer_list.rst
> +     - If enabled by the flags, the checksum is used to provide basic protection against something overwriting the TL in memory. The checksum is set to a value such that the xor over every byte in th
minor: total_size not enclosed in ``.

2024-01-02 11:48 UTC, jmarinho approved these changes

2024-01-02 12:11 UTC, merged