Add 32-bit variants for XFERLIST_SRAM_LAYOUT and XFERLIST_EP_INFO
FirmwareHandoff/firmware_handoff pull request #54
Opened 2024-12-23 15:47 UTC by harrisonmutai-arm

Adds 32-bit versions of the XFERLIST_RW_MEM_LAYOUT and XFERLIST_EP_INFO structures to support booting on 32-bit Arm (aarch32) systems, and corrects the Mbed-TLS heap info heading to fall under the Arm subsection.

2025-01-14 12:31 UTC, sjg20 requested changes

2025-01-14 12:31 UTC, sjg20 commented on source/transfer_list.rst
> +     - Holds a single `entry_point_info` structure.
This structure should be defined here, so please copy over the info from wherever it is kjept.

2025-01-14 17:00 UTC, danh-arm requested changes
Also missing signed-off-by lines

2025-01-15 11:21 UTC, harrisonmutai-arm commented on source/transfer_list.rst
> +     - 0x8
Sorry that's a typo! It should indeed be a 32-bit address.

2025-01-21 12:41 UTC, danh-arm submitted a review, later dismissed
Only minor comments

2025-03-05 01:54 UTC, sjg20 requested changes
I still don't like referring to structures in the guts of a project. You can pull out the C struct definitions and put it in here. That way it can never change without a commit to this project.

2025-03-05 09:27 UTC, harrisonmutai-arm commented
> I still don't like referring to structures in the guts of a project. You can pull out the C struct definitions and put it in here. That way it can never change without a commit to this project.

Could you clarify what you mean by "pull out the C struct definitions"? I believe I’ve already addressed this in your previous request. I added the 32-bit `entry_point_info_t` C structure [1], and the RW memory layout is already defined in its layout table [2].

[1] https://github.com/FirmwareHandoff/firmware_handoff/pull/54/files#diff-75d1d8518f52351181570a42b6cee154a72b2eb15b3771b969f182b2e537b41eR1171
[2] https://github.com/FirmwareHandoff/firmware_handoff/pull/54/files#diff-75d1d8518f52351181570a42b6cee154a72b2eb15b3771b969f182b2e537b41eR1271

2025-03-05 17:18 UTC, sjg20 submitted a review, later dismissed

2025-03-06 21:45 UTC, manish-pandey-arm approved these changes

2025-03-06 22:06 UTC, sjg20 approved these changes

2025-03-06 22:09 UTC, merged